version: "3.8"

services:
  crawler-db:
    container_name: crawler-db
    image: postgres:14
    restart: always
    env_file: .env
    networks:
      - CNPJ_net
    expose:
      - "$POSTGRES_PORT"
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    volumes:
      - ./data:/var/lib/postgresql/data_ 

  crawler:
    container_name: crawler
    depends_on:
      - crawler-db
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - CNPJ_net
    restart: unless-stopped


networks:
  CNPJ_net:

volumes:
  postgres_data: