version: '3.9'

services:
  postgres:
    image: postgres:14
    restart: always
    env_file: .env
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

