version: "3.8"

networks:
  CNPJ_net:

services:
  crawler:
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["python3", "src/main.py"]
    networks:
      - CNPJ_net
    restart: unless-stopped