version: "3.8"

services:
  crawler:
    container_name: crawler
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - CNPJ_net
    restart: unless-stopped
    volumes:
      - ./alembic/versions:/app/alembic/versions:ro
      - .:/app

networks:
  CNPJ_net:
    driver: bridge

  