"""Change audi_file_size_bytes to BigInteger

Revision ID: 6b3261cb1013
Revises: 
Create Date: 2024-07-18 13:59:27.147064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b3261cb1013'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'audit', 'audi_file_size_bytes',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True
    )   
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'audit', 'audi_file_size_bytes',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True
    )
    
    # ### end Alembic commands ###
